Add pointer on class image hover
krbz999/class-pages pull request #21
Opened 2023-09-19 18:38 UTC by InnilToo

2023-09-19 18:44 UTC, InnilToo commented
Or alternatively:
```css
.class-pages-list .gallery img {
    cursor: pointer;
    border: none;
    border-radius: 0.5em;
}
```

2023-09-20 07:19 UTC, krbz999 requested changes

2023-09-20 07:19 UTC, krbz999 commented on styles/pages.css
> +}
```suggestion
  border: none;
  border-radius: 0.5em;
  cursor: pointer;
}
```

2023-09-24 15:11 UTC, krbz999 approved these changes

2023-09-26 11:43 UTC, merged